---

- name: add-repo-key
  rpm_key:
    key: "https://repo.saltstack.com/yum/redhat/7/x86_64/{{ salt_version }}/SALTSTACK-GPG-KEY.pub"
    state: present

- name: add-repo
  yum_repository:
    name: saltstack
    description: "SaltStack {{ salt_version }} repo"
    baseurl: "http://repo.saltstack.com/yum/redhat/$releasever/$basearch/{{salt_version}}"
    gpgcheck: yes
    enabled: yes
    state: present
