---

- name: add-repo-key
  apt_key:
    url: "https://repo.saltproject.io/py3/debian/{{ os_major_release.num }}/amd64/{{ salt_version }}/salt-archive-keyring.gpg" 
    state: present

- name: add-repo
  apt_repository:
    repo: "deb https://repo.saltproject.io/py3/debian/{{ os_major_release.num }}/amd64/{{ salt_version }} {{ os_major_release.name }} main"
    state: present
    filename: 'salt'
